# TODO
# general settings
name: mambairv2_defog
model_type: SRModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: Defog
    type: PairedImageDataset
    dataroot_gt: /home/diandian/Diandian/DD/LV_DATA/Defog/train/gt
    dataroot_lq: /home/diandian/Diandian/DD/LV_DATA/Defog/train/input
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Defog_test
    type: PairedImageDataset
    dataroot_gt: /home/diandian/Diandian/DD/LV_DATA/Defog/test/gt
    dataroot_lq: /home/diandian/Diandian/DD/LV_DATA/Defog/test/input
    io_backend:
      type: disk

# network structures
network_g:
  type: MambaIRv2Light
  upscale: 1
  in_chans: 3
  img_size: 64
  img_range: 1.
  embed_dim: 48
  d_state: 8
  depths: [ 5, 5, 5, 5 ]
  num_heads: [ 4, 4, 4, 4 ]
  window_size: 16
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 5
  mlp_ratio: 1.0
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv'




#  embed_dim: 60
#  d_state: 10
#  mlp_ration: 1.2



#  inp_channels: 3
#  out_channels: 3
#  dim: 48
#  num_blocks: [4,6,6,8]
#  num_refinement_blocks: 4
#  heads: [1,2,4,8]
#  ffn_expansion_factor: 2.66
#  bias: False
#  LayerNorm_type: WithBias
#  dual_pixel_task: False


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 100
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
